package com.cyril.replug.navigation

const val ROUTE_SPLASH = "splash"
const val ROUTE_ONBOARDING1 = "onboarding1"
const val ROUTE_HOME = "home"
const val ROUTE_LOGIN = "login"
const val ROUTE_REGISTER = "register"
const val ROUTE_CONVERSATION = "conversation"
const val ROUTE_ABOUT = "about"
const val ROUTE_SCAFFOLD = "scaffold"
const val ROUTE_ONBOARDING2 = "onboarding2"
const val ROUTE_ONBOARDING3 = "onboarding3"
const val ROUTE_SEARCH = "search"
const val ROUTE_WISHLIST = "wishlist"
const val ROUTE_PROFILE = "profile"
const val ROUTE_EPROFILE = "eprofile"
const val ROUTE_RECYCLE = "recycle"
const val ROUTE_ADD = "add"
const val ROUTE_SELL = "sell"
const val ROUTE_CONTACT = "contact"
const val ROUTE_ORDERS = "orders"
const val ROUTE_NOTIFICATION = "notification"
const val ROUTE_RECYCLED_PRODUCTS = "recycledproducts"
const val ROUTE_PRODUCT_DETAIL = "productdetail"
const val ROUTE_CHAT_INBOX = "chatInbox"


